Repository openedx/frontend-app-profile, pull requests merged in 2023-11, with the labels that each got.

#865 feat: Fields visibility and visibility forms (palm.master)
  src/profile/ProfilePage.jsx
  src/profile/ProfilePage.test.jsx
  src/profile/__snapshots__/ProfilePage.test.jsx.snap
  src/profile/data/sagas.js
  src/profile/data/selectors.js
Labels: waiting on author, open-source-contribution

#888 fix: trim long text in form controls and username block
  src/profile/ProfilePage.jsx
  src/profile/__snapshots__/ProfilePage.test.jsx.snap
  src/profile/forms/__snapshots__/SocialLinks.test.jsx.snap
  src/profile/forms/elements/Visibility.jsx
Labels: open-source-contribution

#887 fix: trim long text in form controls and username block
  src/profile/ProfilePage.jsx
  src/profile/__snapshots__/ProfilePage.test.jsx.snap
  src/profile/forms/__snapshots__/SocialLinks.test.jsx.snap
  src/profile/forms/elements/Visibility.jsx
Labels: open-source-contribution, backport

#899 fix: trim long text in form controls and username block
  src/profile/ProfilePage.jsx
  src/profile/__snapshots__/ProfilePage.test.jsx.snap
  src/profile/forms/__snapshots__/SocialLinks.test.jsx.snap
  src/profile/forms/elements/Visibility.jsx
Labels: open-source-contribution, waiting for eng review, needs maintainer attention
